/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    ContentBox: typeof import('./src/components/ContentBox.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Feed: typeof import('./src/components/FeedList.vue')['default']
    FeedList: typeof import('./src/components/FeedList.vue')['default']
    FollowBtn: typeof import('./src/components/FollowBtn.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PinnedPost: typeof import('./src/components/PinnedPost.vue')['default']
    RegularPost: typeof import('./src/components/RegularPost.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPage: typeof import('./src/components/UserSearch.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    UserSearch: typeof import('./src/components/UserSearch.vue')['default']
  }
}
